### ISSUE TITLE
Violazione Copyright

### ISSUE THREAD

**Issue by M9k** [gabrielrovesti/Metodi-e-tecnologie-per-lo-sviluppo-software-UniPD#1]
I libri riportati e parte del materiale violano il copyright, esplicito e/o implicito.

Ad esempio:
https://github.com/gabrielrovesti/Metodi-e-tecnologie-per-lo-sviluppo-software-UniPD/blob/main/Libri/Martin%20Fowler%20-%20Continuous%20Delivery.pdf
![immagine](https://github.com/gabrielrovesti/Metodi-e-tecnologie-per-lo-sviluppo-software-UniPD/assets/9288402/dcdafd50-529e-4c90-b8b2-8696248e2bec)

**Comment by gabrielrovesti** [comment]
Grazie mille della segnalazione; essendo stata intesa come fonte di appunti interni, li avevo scaricati e poi tenuti qui, ma hai perfettamente ragione. Non esitare a dirmi altre cose che sistemo

**Comment by AlecsFerra** [comment]
I file sono ancora presenti nella history del repository, la issue non è risolta.
